version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start brewery_project
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/brewery_project
      ENV: development
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
